### PR TITLE
feat: create new account helper function

### LINKED ISSUE #1052: Enable customisable `AccountCreate` in `utilities_for_test.go`
## 🆕🐥 First Timers Only

This issue is reserved for people who have never contributed to [Hedera](https://hedera.com) or any open source project in general.
We know that creating a pull request (PR) is a major barrier for new contributors.
The goal of this issue and all other issues labeled by [**'Good First Issue'**](https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Ahashgraph+archived%3Afalse+label%3A%22Good+First+Issue%22+) is to help you make your first contribution to Hedera.

## 👾 Description of the issue
- We need a more customisable `accountCreate` helper method in our `utilities_for_test`.

### Proposed Solution:

 - Remove `createAccountHelper` from `max_auto_associations_e2e_test.go` and add `createAccount` method to `utilities_for_test.go` similar to `createFungibleToken` and `createNft` methods in the same file.
 - The new method should do the following:
 1.  Create a new private key that will be associated with this account.
 2. Create a new `AccountCreateTransaction` with the default values set.
 3. Loop through the customizer operations and call `opts`.
 4. Execute the transaction and get the receipt.
 5. If error occurred - return it, if not - return the new `AccountID` from the receipt
 - Refactor the usages of `createAccountHelper` to use the new method.

### Example Implementation

```go
// utilities_for_test.go

func createAccount(env *IntegrationTestEnv, opts ...AccountCreateTransactionCustomizer) (hedera.AccountID, error) {
	newKey, err := PrivateKeyGenerateEd25519()
	require.NoError(t, err)

	accountCreate, err := NewAccountCreateTransaction().
		SetKey(newKey).
		SetNodeAccountIDs(env.NodeAccountIDs).
		SetInitialBalance(NewHbar(1)).
		Execute(env.Client)
	require.NoError(t, err)
	
    // The rest is similar to createFungibleToken and createNft
}
```

## 📋 Step by step guide to do a contribution

If you have never contributed to an open source project at GitHub, the following step-by-step guide will introduce you to the workflow. More information and concrete samples for shell commands for each step can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md) file.
A more detailed general documentation of the GitHub PR workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] **Claim this issue:** Comment below that you are interested in working on the issue
- [ ] **Wait for assignment:** A community member with the given rights will add you as an assignee of the issue
- [ ] **Fork the repository:** You can do that in GitHub (by simply clicking the 'fork' button).
- [ ] **Check out the forked repository**
- [ ] **Create a feature branch** for the issue. We do not have a hard naming definition for branches but it is best practice to prefix the branch name with the issue id.
- [ ] **Solve the issue** in your branch.
- [ ] **Commit your changes:** Here, it is needed to add `sign-off` information to the commit to accept the "Developer Certificate of Origin" (https://developercertificate.org). More details can be found in our [CONTRIBUTING.md](https://github.com/hashgraph/.github/blob/main/CONTRIBUTING.md)
- [ ] **Start a Pull Request (PR)**: We have a pattern for naming pull requests that a GitHub Action checks. We use that pattern to support the creation of automatic release notes.
- [ ] **Check GitHub Actions:** Several GitHub Actions will be triggered automatically for each PR. If a GitHub Action fails and you do not understand the cause of that error do not hesitate to add a comment to the PR and ask the Hedera developer community for support.
- [ ] **Wait for reviews:** Members of the Hedera developer community will review your PR. If a reviewer finds any missing pieces or a problem, he or she will start a discussion with you and describe the next steps for solving the problem.
- [ ] **You did it 🎉:** We will merge the fix in the develop branch. Thanks for being part of the Hedera community as an open-source contributor ❤️

## 🎉 Contribute to Hacktoberfest

Solve this issue as part of the [Hacktoberfest](https://hacktoberfest.digitalocean.com) event and get a chance to receive cool goodies like a T-Shirt. 🎽

## 🤔 Additional Information

If you have any questions, just ask us directly in this issue by adding a comment. You can join our community chat at [Discord](https://hedera.com/discord). A general manual about open-source contributions can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

### PR DESCRIPTION
**Pull request by Mujhtech**
**Description**:

This pull request refactors the account helper functions in the codebase. It introduces a new helper function for creating a new account and removes the old account helper function. The refactoring also includes replacing the old account helper function with the new one in relevant parts of the code.

**Related issue(s)**:

Fixes #1052 

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [x] Tested (unit, integration, etc.)

### CODE REVIEW

**Comment by Mujhtech** [comment]
You can check it now @0xivanov

**Comment by samswag** [comment]
@Mujhtech 

Can you also check this out too:

https://github.com/hashgraph/hedera-sdk-go/issues/1052#issuecomment-2397835382

**Comment by Mujhtech** [comment]
Thanks for calling my attention, @samswag. I didn't see the comment before.

**Review by 0xivanov — COMMENTED** [review]
Test build is failing.

**Comment by Mujhtech** [comment]
> Test build is failing.

fixed

**Comment by 0xivanov** [comment]
@Mujhtech  try running the following commands to verify the build:
```
go test -tags="e2e" 
```

```
go test -tags="unit" 
```

**Comment by Mujhtech** [comment]
> go test -tags="unit"

Yeah, done and fix in the last commit

**Review by 0xivanov — APPROVED** [review]
LGTM, TY @Mujhtech

**Pull request merged**
